import "./globals.css";
import { FaBeer } from "react-icons/fa";
import { Poppins } from "next/font/google";
import { faCircleUser } from "@fortawesome/free-regular-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { config } from "@fortawesome/fontawesome-svg-core";

import { HideMenuButton } from "@/app/HideMenuButton";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Notification } from "@/app/Notification";
import { ThemeButton } from "@/app/ThemeButton";
import { SearchBlock } from "@/app/SearchBlock";
import Providers from "@/app/Providers";
config.autoAddCss = false;

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-[#f6f9ff]`}>
        <Providers>
          <div className="text-[#7b8190]">
            <div className="flex w-full justify-between bg-white fixed top-0 z-20">
              <div className="p-5 w-full flex justify-between dark:bg-neutral-600 shadow-md">
                <div className="flex justify-between items-center w-52">
                  <div className="font-bold text-indigo-900 text-3xl dark:text-yellow-300">
                    LunaAdmin
                  </div>{" "}
                  <FaBeer />
                  <HideMenuButton />
                </div>
                <div className="flex gap-5 items-center">
                  <SearchBlock />
                  <ThemeButton />
                  <Notification />
                  <FontAwesomeIcon
                    className="text-[#adb4d2]-500"
                    icon={faCircleUser}
                  />
                </div>
              </div>
            </div>
            <div className="flex w-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
